const BAD_REQUEST_CODE = 400;
const AUTH_ERROR_CODE = 401;
const FORBIDDEN_CODE = 403;
const NOT_FOUND_CODE = 404;
const CONFLICT_CODE = 409;
const SERVER_ERROR_CODE = 500;
const SERVER_ERROR_MESSAGE = 'На сервере произошла ошибка.';
const BAD_REQUEST_MESSAGE = 'Введены некорректные данные.';

module.exports = {
  BAD_REQUEST_CODE,
  AUTH_ERROR_CODE,
  FORBIDDEN_CODE,
  NOT_FOUND_CODE,
  CONFLICT_CODE,
  SERVER_ERROR_CODE,
  SERVER_ERROR_MESSAGE,
  BAD_REQUEST_MESSAGE,
};
